# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
url="https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo=pd.read_csv(url,sep='\t')
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 4. See the first 10 entries

In [11]:
df=pd.DataFrame(chipo)
df.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [12]:
# Solution 1
df.shape[0]

4622

In [34]:
# Solution 2
df.describe
df.head(20)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,7,1,Chips and Guacamole,NaN,$4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,9,2,Canned Soda,[Sprite],$2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75

### Step 6. What is the number of columns in the dataset?

In [25]:
df.shape[1]

5

### Step 7. Print the name of all the columns.

In [26]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [27]:
df.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [ ]:
j=df.groupby("item_name")["quantity"].sum()
j= j.sort_values(ascending=False)
j=pd.DataFrame(j)
j.iloc[0]

quantity    761
Name: Chicken Bowl, dtype: int64

### Step 10. For the most-ordered item, how many items were ordered?

In [55]:
j["quantity"].head(1)

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

### Step 11. What was the most ordered item in the choice_description column?

In [56]:
j["choice_description"].head(1)

KeyError: 'choice_description'

### Step 12. How many items were orderd in total?

In [50]:
j["quantity"].sum()

np.int64(4972)

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [4]:
chipo.item_price.dtype

dtype('O')

#### Step 13.b. Create a lambda function and change the type of item price

In [12]:
put=lambda x : float(x[1:-1])
df["item_price"]=df["item_price"].apply(put)
# df["item_price"].dtype

#### Step 13.c. Check the item price type

In [13]:
df["item_price"].dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [ ]:
# h=(j["quantity"]*j["item_price"]).sum()
# print(h)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",7342.73
Chicken Burrito,497303,591,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",5575.82
Chips and Guacamole,449959,506,0,2201.04
Steak Burrito,328437,386,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",3851.43
Canned Soft Drink,304753,351,[Coke][Sprite][Coke][Coke][Lemonade][Sprite][D...,438.75
Chips,208004,230,0,494.34
Steak Bowl,193752,221,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",2260.19
Bottled Water,175944,211,0,302.56
Chips and Fresh Tomato Salsa,100419,130,0,361.36
Canned Soda,76396,126,[Sprite][Dr. Pepper][Mountain Dew][Sprite][Dr....,137.34
Chicken Salad Bowl,117104,123,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",1228.75
Chicken Soft Tacos,98395,120,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",1108.09
Side of Chips,84769,110,0,185.90
Veggie Burrito,80962,97,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",934.77
Barbacoa Burrito,74718,91,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",894.75
Veggie Bowl,72270,87,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",867.99
Carnitas Bowl,62742,71,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",736.71
Barbacoa Bowl,53972,66,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",672.36
Carnitas Burrito,51652,60,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",597.83
Steak Soft Tacos,50177,56,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",536.05
6 Pack Soft Drink,52322,55,[Sprite][Diet Coke][Coke][Diet Coke][Diet Coke...,356.95
Chips and Tomatillo Red Chili Salsa,45556,50,0,147.50
Chicken Crispy Tacos,47382,50,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",472.13
Chips and Tomatillo Green Chili Salsa,41170,45,0,132.75
Carnitas Soft Tacos,37673,40,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",375.94
Steak Crispy Tacos,35818,36,"[Fresh Tomato Salsa, Sour Cream][[Roasted Chil...",357.34
Chips and Tomatillo-Green Chili Salsa,21826,33,0,78.87
Steak Salad Bowl,29590,31,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",343.59
Nantucket Nectar,21814,29,[Apple][Pomegranate Cherry][Pineapple Orange B...,98.31
Chips and Tomatillo-Red Chili Salsa,18344,25,0,59.75
Barbacoa Soft Tacos,18725,25,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",250.46
Chips and Roasted Chili Corn Salsa,14999,23,0,67.85
Izze,10587,20,[Clementine][Grapefruit][Blackberry][Blackberr...,67.80
Veggie Salad Bowl,17303,18,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",182.50
Chips and Roasted Chili-Corn Salsa,17462,18,0,43.02
Barbacoa Crispy Tacos,5613,12,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",120.21
Barbacoa Salad Bowl,9708,10,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",106.40
Chicken Salad,10465,9,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",81.09
Carnitas Crispy Tacos,5868,8,[Roasted Chili Corn Salsa][Tomatillo Green Chi...,77.96
Veggie Soft Tacos,5520,8,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",73.96
Burrito,1550,6,"[Adobo-Marinated and Grilled Chicken, Pinto Be...",44.40
Veggie Salad,7265,6,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",50.94
Carnitas Salad Bowl,6693,6,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",66.34
Bowl,472,4,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",29.60
Steak Salad,2362,4,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",35.66
Salad,1150,2,"[Brown Rice, Adobo-Marinated and Grilled Chick...",14.80
Crispy Tacos,434,2,[Adobo-Marinated and Grilled Steak][Adobo-Mari...,14.80
Chips and Mild Fresh Tomato Salsa,279,1,0,3.00
Carnitas Salad,1500,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.99
Veggie Crispy Tacos,668,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 15. How many orders were made in the period?

In [ ]:
df.order_id.value_counts().count()

(3335,)

### Step 16. What is the average revenue amount per order?

In [3]:
# Solution 1

In [4]:
# Solution 2

### Step 17. How many different items are sold?

In [65]:
df["item_name"].value_counts().count()

np.int64(50)